# Generated by Django 3.2.3 on 2021-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_listing',
            field=models.ManyToManyField(blank=True, related_name='bid_listing', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_listing',
            field=models.ManyToManyField(blank=True, related_name='comment_listing', to='auctions.Listing'),
        ),
    ]
