# Generated by Django 3.2.3 on 2021-06-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='my_bids',
            field=models.ManyToManyField(blank=True, related_name='my_bids', to='auctions.Bid'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_comments',
            field=models.ManyToManyField(blank=True, related_name='my_comments', to='auctions.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_listings',
            field=models.ManyToManyField(blank=True, related_name='my_listings', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_watchlist',
            field=models.ManyToManyField(blank=True, related_name='my_watchlist', to='auctions.Listing'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
