# Generated by Django 3.2.3 on 2021-06-14 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210614_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
