# Generated by Django 3.2.3 on 2021-06-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('GN', 'General'), ('MA', 'Mens Apparel'), ('WA', 'Womens Apparel'), ('SP', 'Sports'), ('HM', 'Home'), ('TY', 'Toys')], default='GN', max_length=2),
        ),
    ]
